version: "3.3"
services:

  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB}
    volumes:
      - ./server/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    environment:
      APP_ENV: ${APP_ENV}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB: ${DB}
      HOST: ${HOST}
      PORT: ${PORT}
      DB_DIALECT: ${DB_DIALECT}
    restart: always
    build: ./server
    ports:
      - "5001:5000"
    depends_on:
      - postgres
    working_dir: /app
    command: npm run start
